-- =====================================================
-- Workout Tracker - Row Level Security Policies
-- Migration: 20240101000002
-- =====================================================

-- =====================================================
-- USERS TABLE POLICIES
-- =====================================================

CREATE POLICY "Users can view own profile"
ON public.users FOR SELECT
USING (auth.uid() = id);

CREATE POLICY "Users can update own profile"
ON public.users FOR UPDATE
USING (auth.uid() = id);

-- =====================================================
-- WORKOUT PROGRAMS POLICIES
-- =====================================================

CREATE POLICY "Users can view own programs"
ON public.workout_programs FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can create own programs"
ON public.workout_programs FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own programs"
ON public.workout_programs FOR UPDATE
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own programs"
ON public.workout_programs FOR DELETE
USING (auth.uid() = user_id);

-- =====================================================
-- PROGRAM DAYS POLICIES
-- =====================================================

CREATE POLICY "Users can view program days"
ON public.program_days FOR SELECT
USING (
  EXISTS (
    SELECT 1 FROM workout_programs
    WHERE id = program_days.program_id
    AND user_id = auth.uid()
  )
);

CREATE POLICY "Users can manage program days"
ON public.program_days FOR ALL
USING (
  EXISTS (
    SELECT 1 FROM workout_programs
    WHERE id = program_days.program_id
    AND user_id = auth.uid()
  )
);

-- =====================================================
-- WORKOUTS POLICIES
-- =====================================================

CREATE POLICY "Users can view own workouts"
ON public.workouts FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can create own workouts"
ON public.workouts FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own workouts"
ON public.workouts FOR UPDATE
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own workouts"
ON public.workouts FOR DELETE
USING (auth.uid() = user_id);

-- =====================================================
-- EXERCISES POLICIES
-- =====================================================

CREATE POLICY "Users can view exercises in own workouts"
ON public.exercises FOR SELECT
USING (
  EXISTS (
    SELECT 1 FROM workouts
    WHERE id = exercises.workout_id
    AND user_id = auth.uid()
  )
);

CREATE POLICY "Users can manage exercises in own workouts"
ON public.exercises FOR ALL
USING (
  EXISTS (
    SELECT 1 FROM workouts
    WHERE id = exercises.workout_id
    AND user_id = auth.uid()
  )
);

-- =====================================================
-- EXERCISE SETS POLICIES
-- =====================================================

CREATE POLICY "Users can view sets in own exercises"
ON public.exercise_sets FOR SELECT
USING (
  EXISTS (
    SELECT 1 FROM exercises e
    JOIN workouts w ON w.id = e.workout_id
    WHERE e.id = exercise_sets.exercise_id
    AND w.user_id = auth.uid()
  )
);

CREATE POLICY "Users can manage sets in own exercises"
ON public.exercise_sets FOR ALL
USING (
  EXISTS (
    SELECT 1 FROM exercises e
    JOIN workouts w ON w.id = e.workout_id
    WHERE e.id = exercise_sets.exercise_id
    AND w.user_id = auth.uid()
  )
);

-- =====================================================
-- BODY WEIGHT LOGS POLICIES
-- =====================================================

CREATE POLICY "Users can view own weight logs"
ON public.body_weight_logs FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can create own weight logs"
ON public.body_weight_logs FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own weight logs"
ON public.body_weight_logs FOR UPDATE
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own weight logs"
ON public.body_weight_logs FOR DELETE
USING (auth.uid() = user_id);

-- =====================================================
-- PERSONAL RECORDS POLICIES
-- =====================================================

CREATE POLICY "Users can view own PRs"
ON public.personal_records FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own PRs"
ON public.personal_records FOR DELETE
USING (auth.uid() = user_id);

-- Note: PRs are auto-generated by triggers, but we allow manual inserts for migration purposes
CREATE POLICY "Users can create own PRs"
ON public.personal_records FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- =====================================================
-- GAMIFICATION DATA POLICIES
-- =====================================================

CREATE POLICY "Users can view own gamification data"
ON public.gamification_data FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can update own gamification data"
ON public.gamification_data FOR UPDATE
USING (auth.uid() = user_id);

-- =====================================================
-- READINESS LOGS POLICIES
-- =====================================================

CREATE POLICY "Users can view own readiness logs"
ON public.readiness_logs FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Users can create own readiness logs"
ON public.readiness_logs FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own readiness logs"
ON public.readiness_logs FOR UPDATE
USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own readiness logs"
ON public.readiness_logs FOR DELETE
USING (auth.uid() = user_id);

-- =====================================================
-- EXERCISE LIBRARY POLICIES
-- =====================================================

CREATE POLICY "Anyone can view exercise library"
ON public.exercise_library FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Users can create custom exercises"
ON public.exercise_library FOR INSERT
WITH CHECK (auth.uid() = created_by AND is_custom = true);

CREATE POLICY "Users can update own custom exercises"
ON public.exercise_library FOR UPDATE
USING (auth.uid() = created_by AND is_custom = true);

CREATE POLICY "Users can delete own custom exercises"
ON public.exercise_library FOR DELETE
USING (auth.uid() = created_by AND is_custom = true);

