// This file will be auto-generated by Supabase CLI
// Run: supabase gen types typescript --linked > lib/supabase/types.ts
// For now, we'll create a manual type definition based on the schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type ExerciseType = 'strength' | 'cardio'
export type MachineType = 'treadmill' | 'bike' | 'elliptical' | 'rowing' | 'stairmaster' | 'other'
export type RecordType = 'max_weight' | 'max_volume' | 'max_reps'
export type DifficultyLevel = 'beginner' | 'intermediate' | 'advanced'

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          created_at: string
          updated_at: string
          settings: Json
        }
        Insert: {
          id: string
          email: string
          created_at?: string
          updated_at?: string
          settings?: Json
        }
        Update: {
          id?: string
          email?: string
          created_at?: string
          updated_at?: string
          settings?: Json
        }
      }
      workout_programs: {
        Row: {
          id: string
          user_id: string
          name: string
          description: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          description?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          description?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }
      program_days: {
        Row: {
          id: string
          program_id: string
          day_name: string
          day_order: number
          muscle_groups: string[]
          created_at: string
        }
        Insert: {
          id?: string
          program_id: string
          day_name: string
          day_order: number
          muscle_groups?: string[]
          created_at?: string
        }
        Update: {
          id?: string
          program_id?: string
          day_name?: string
          day_order?: number
          muscle_groups?: string[]
          created_at?: string
        }
      }
      workouts: {
        Row: {
          id: string
          user_id: string
          program_day_id: string | null
          workout_date: string
          start_time: string
          end_time: string | null
          is_completed: boolean
          notes: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          program_day_id?: string | null
          workout_date?: string
          start_time?: string
          end_time?: string | null
          is_completed?: boolean
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          program_day_id?: string | null
          workout_date?: string
          start_time?: string
          end_time?: string | null
          is_completed?: boolean
          notes?: string | null
          created_at?: string
          updated_at?: string
        }
      }
      exercises: {
        Row: {
          id: string
          workout_id: string
          exercise_type: ExerciseType
          exercise_name: string
          order_index: number
          created_at: string
          sets_completed: number
          target_sets: number | null
          target_reps_min: number | null
          target_reps_max: number | null
          machine_type: MachineType | null
          duration_minutes: number | null
          distance: number | null
          avg_pace: number | null
          calories: number | null
        }
        Insert: {
          id?: string
          workout_id: string
          exercise_type: ExerciseType
          exercise_name: string
          order_index?: number
          created_at?: string
          sets_completed?: number
          target_sets?: number | null
          target_reps_min?: number | null
          target_reps_max?: number | null
          machine_type?: MachineType | null
          duration_minutes?: number | null
          distance?: number | null
          avg_pace?: number | null
          calories?: number | null
        }
        Update: {
          id?: string
          workout_id?: string
          exercise_type?: ExerciseType
          exercise_name?: string
          order_index?: number
          created_at?: string
          sets_completed?: number
          target_sets?: number | null
          target_reps_min?: number | null
          target_reps_max?: number | null
          machine_type?: MachineType | null
          duration_minutes?: number | null
          distance?: number | null
          avg_pace?: number | null
          calories?: number | null
        }
      }
      exercise_sets: {
        Row: {
          id: string
          exercise_id: string
          set_number: number
          reps: number
          weight: number
          is_warmup: boolean
          is_completed: boolean
          rpe: number | null
          created_at: string
        }
        Insert: {
          id?: string
          exercise_id: string
          set_number: number
          reps: number
          weight?: number
          is_warmup?: boolean
          is_completed?: boolean
          rpe?: number | null
          created_at?: string
        }
        Update: {
          id?: string
          exercise_id?: string
          set_number?: number
          reps?: number
          weight?: number
          is_warmup?: boolean
          is_completed?: boolean
          rpe?: number | null
          created_at?: string
        }
      }
      body_weight_logs: {
        Row: {
          id: string
          user_id: string
          weight: number
          log_date: string
          notes: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          weight: number
          log_date?: string
          notes?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          weight?: number
          log_date?: string
          notes?: string | null
          created_at?: string
        }
      }
      personal_records: {
        Row: {
          id: string
          user_id: string
          exercise_name: string
          record_type: RecordType
          value: number
          achieved_date: string
          workout_id: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          exercise_name: string
          record_type: RecordType
          value: number
          achieved_date?: string
          workout_id?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          exercise_name?: string
          record_type?: RecordType
          value?: number
          achieved_date?: string
          workout_id?: string | null
          created_at?: string
        }
      }
      gamification_data: {
        Row: {
          id: string
          user_id: string
          total_points: number
          current_streak: number
          longest_streak: number
          total_workouts: number
          last_workout_date: string | null
          weekly_stats: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          total_points?: number
          current_streak?: number
          longest_streak?: number
          total_workouts?: number
          last_workout_date?: string | null
          weekly_stats?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          total_points?: number
          current_streak?: number
          longest_streak?: number
          total_workouts?: number
          last_workout_date?: string | null
          weekly_stats?: Json
          created_at?: string
          updated_at?: string
        }
      }
      readiness_logs: {
        Row: {
          id: string
          user_id: string
          log_date: string
          sleep_quality: number
          energy_level: number
          joint_comfort: number
          overall_readiness: number
          notes: string | null
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          log_date?: string
          sleep_quality: number
          energy_level: number
          joint_comfort: number
          notes?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          log_date?: string
          sleep_quality?: number
          energy_level?: number
          joint_comfort?: number
          notes?: string | null
          created_at?: string
        }
      }
      exercise_library: {
        Row: {
          id: string
          exercise_name: string
          exercise_type: ExerciseType
          primary_muscle_groups: string[]
          secondary_muscle_groups: string[]
          equipment_needed: string[]
          difficulty_level: DifficultyLevel | null
          description: string | null
          video_url: string | null
          is_custom: boolean
          created_by: string | null
          created_at: string
        }
        Insert: {
          id?: string
          exercise_name: string
          exercise_type: ExerciseType
          primary_muscle_groups: string[]
          secondary_muscle_groups?: string[]
          equipment_needed?: string[]
          difficulty_level?: DifficultyLevel | null
          description?: string | null
          video_url?: string | null
          is_custom?: boolean
          created_by?: string | null
          created_at?: string
        }
        Update: {
          id?: string
          exercise_name?: string
          exercise_type?: ExerciseType
          primary_muscle_groups?: string[]
          secondary_muscle_groups?: string[]
          equipment_needed?: string[]
          difficulty_level?: DifficultyLevel | null
          description?: string | null
          video_url?: string | null
          is_custom?: boolean
          created_by?: string | null
          created_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      calculate_exercise_volume: {
        Args: { exercise_uuid: string }
        Returns: number
      }
      calculate_workout_volume: {
        Args: { workout_uuid: string }
        Returns: number
      }
      update_workout_streak: {
        Args: { user_uuid: string }
        Returns: void
      }
      reset_weekly_stats: {
        Args: Record<string, never>
        Returns: void
      }
      create_default_program_for_user: {
        Args: { user_uuid: string }
        Returns: string
      }
    }
    Enums: {
      exercise_type: ExerciseType
      machine_type: MachineType
      record_type: RecordType
    }
  }
}

